je suis en trai de créer un formulaire en python qui est rattacher à une base de donée locale.
mais je rencontre un probleme au niveau de la ligne 92


J'ai trouver mon erreur

voici le code qui marchait pas   || prenomEntre = Entry(contenu,  fontEntre)
et le nouvau code est   || prenomEntre = Entry(contenu,  font=fontEntre)




Mardi 24/08/2021

"Logiquement quand on finit des remplir les champs, on appui sur valider. Ensuite on appui sur 'Liste'  pour voir notre liste. Mais dans la déclaration, c-a-d  dans mes importations,j'ai Ecris From PIL import Image,ImageTk, mais on me dit  que le fuchier PIL n'est pas definit"